smu88/app_main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import IndexView, ProjectListView, FeedbackFormView, InnovationsListView


app_name = 'app_main'

urlpatterns = [
    path('', cache_page(30)(IndexView.as_view()), name='index'),
    path('projects/', cache_page(20)(ProjectListView.as_view()), name='projects'),
    path('feedback/', FeedbackFormView.as_view(), name='feedback'),
    path('innovations/', cache_page(20)(InnovationsListView.as_view()), name='innovations'),
]

smu88/smu88/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_main.urls', namespace='app_main')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

smu88/app_main/models.py
from django.db import models

from ckeditor_uploader.fields import RichTextUploadingField


def project_image_directory_path(instance, filename):
    """Create path for save photo """
    return f'{instance.project.name}/{filename}'


class AboutInfo(models.Model):
    title = models.CharField(max_length=255, verbose_name='заголовок')
    text = RichTextUploadingField()

    class Meta:
        verbose_name = 'текст на главной'
        verbose_name_plural = 'текст на главной'

    def __str__(self):
        return f'{self.title}'


class Project(models.Model):
    """Строительный объект(ЖК)"""

    name = models.CharField(max_length=255, verbose_name='название объекта')
    slug = models.SlugField(max_length=255, verbose_name='slug объекта')

    class Meta:
        verbose_name = 'проект'
        verbose_name_plural = 'проект'

    def __str__(self):
        return f'{self.name}'


class ProjectPhoto(models.Model):
    """Фото для проекта(объектов строительства)"""

    image = models.ImageField(upload_to=project_image_directory_path, verbose_name='фото проекта')
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='image', verbose_name='проект')

    class Meta:
        verbose_name = 'фото проекта'
        verbose_name_plural = 'фото проекта'

    def __str__(self):
        return f'{self.project}'


class Innovation(models.Model):
    """Раздел инноваций на сайте"""

    title = models.CharField(max_length=255, verbose_name='заголовок инновации')
    slug = models.SlugField(max_length=255, verbose_name='slug инновации')
    text = RichTextUploadingField()
    image = models.ImageField(upload_to='innovations_image', verbose_name='картинка')

    class Meta:
        verbose_name = 'инновация'
        verbose_name_plural = 'инновации'

    def __str__(self):
        return f'{self.title}'


class Iframe(models.Model):
    title = models.CharField(max_length=255, verbose_name='название формы')
    iframe = models.TextField(verbose_name='iframe форма')

    class Meta:
        verbose_name = 'форма iframe'
        verbose_name_plural = 'формы iframe'

    def __str__(self):
        return f'{self.title}'

smu88/app_main/views.py
from django.views.generic import TemplateView, ListView

from .models import AboutInfo, Project, Innovation, Iframe


class IndexView(TemplateView):
    template_name = 'app_main/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['about'] = AboutInfo.objects.get(pk=1)

        return context


class ProjectListView(ListView):
    model = Project
    context_object_name = 'projects'
    template_name = 'app_main/projects.html'


class FeedbackFormView(ListView):
    model = Iframe
    context_object_name = 'iframes'
    template_name = 'app_main/feedback_form.html'


class InnovationsListView(ListView):
    model = Innovation
    context_object_name = 'innovations'
    template_name = 'app_main/innovations.html'

smu88/app_main/templates/app_main/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;1,100&display=swap" rel="stylesheet">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'image/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'image/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'image/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'image/favicon/site.webmanifest' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar bg-body-tertiary bg-dark" data-bs-theme="dark">
  <div class="container-fluid">
      <div class="d-flex">
      </div>
       <span class="navbar-text">
            <a class="{% if request.path == '/' %} active-link {% endif %}" href="{% url 'app_main:index' %}">О СМУ-88</a> |  &nbsp;
            <a href="https://smu88.group/" target="_blank">ПРОДАЖИ</a> |  &nbsp;
            <a class="{% if request.path == '/projects/' %} active-link {% endif %}" href="{% url 'app_main:projects' %}">РЕАЛИЗОВАННЫЕ ОБЪЕКТЫ</a> |  &nbsp;
            <a class="{% if request.path == '/feedback/' %} active-link {% endif %}" href="{% url 'app_main:feedback' %}">ФОРМЫ ОБРАТНОЙ СВЯЗИ</a> |  &nbsp;
            <a class="{% if request.path == '/innovations/' %} active-link {% endif %}" href="{% url 'app_main:innovations' %}">ТЕХНЛОГИЧЕСКИЕ ИННОВАЦИИ</a>
      </span>
  </div>
</nav>
  {% block content %}
  {% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>

smu88/app_main/templates/app_main/feedback_form.html
{% extends 'app_main/base.html' %}

{% block title %} Форма обратной связи {% endblock %}

{% block content %}
    <div class="container text-center py-5">
        <div class="row">
            <div class="col">
                {% for iframe in iframes %}
                    <br>
                    <h3>{{ iframe.title }}</h3>
                    <br>
                    <p>{{ iframe.iframe | safe }}</p>
                    <hr>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

smu88/app_main/templates/app_main/index.html
{% extends 'app_main/base.html' %}

{% block title %} Главная страница | СМУ-88 {% endblock %}

{% block content %}
    <div class="container text-center py-5">
        <div class="row">
            <div class="col">
                <h2>{{ about.title }}</h2>
                {{ about.text | safe }}
            </div>
        </div>
    </div>
{% endblock %}

smu88/app_main/templates/app_main/innovations.html
{% extends 'app_main/base.html' %}
{% load humanize %}


{% block title %} Технологические инновации {% endblock %}

{% block content %}
    <div class="container text-center py-5">
        <div class="row">
            <div class="col-2">
            </div>
            <div class="col-8">
               {% for innovation in innovations %}
                <br>
                    <div class="card mb-3">
                        {% if innovation.image %}
                      <img src="/media/{{ innovation.image }}" class="card-img-top" alt="{{ innovation.title }}">
                        {% endif %}
                      <div class="card-body">
                        <h5 class="card-title">{{ innovation.title }}</h5>
                        <p class="card-text"> {{ innovation.text | safe }}</p>
                        <p class="card-text"><small class="text-body-secondary">{{ innovation.created_at | naturaltime}}</small></p>
                      </div>
                    </div>
                {% endfor %}
            </div>
            <div class="col-2">
            </div>
        </div>
    </div>
{% endblock %}

smu88/app_main/templates/app_main/projects.html
{% extends 'app_main/base.html' %}

{% block title %} Реализованные объекты {% endblock %}

{% block content %}
    <div class="container text-center py-5">
        <div class="row">
            <div class="col-2">

            </div>
            <div class="col">
                {% for project in projects %}
                    <br>
                    <h3>{{ project.name }}</h3>
                    <br>
                    <div id="{{ project.id }}" class="carousel slide" data-bs-ride="carousel">
                      <div class="carousel-inner">
                          {% for image in project.image.all %}
                        <div class="carousel-item active" data-bs-interval="3000">
                          <img src="/media/{{ image.image }}" class="d-block w-100" alt="{{ project.name }}" height="300px">
                        </div>
                        {% endfor %}
                      </div>
                      <button class="carousel-control-prev" type="button" data-bs-target="#{{ project.id }}" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                      </button>
                      <button class="carousel-control-next" type="button" data-bs-target="#{{ project.id }}" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                      </button>
                    </div>
                    <hr>
                {% endfor %}
            </div>
            <div class="col-2">

            </div>
        </div>
    </div>
{% endblock %}